-- phase: expand
-- OpenVibe.VIP on PostgreSQL (ADR-035, roadmap WS-X2): the tables as they were on SQLite (converted by openvibe-sdk
-- tools/asyncify/sqlite-schema-to-pg: text COLLATE "C" compares like SQLite, integers are bigint, identities keep their ids),
-- then the openvibe-publishing stores and the openvibe-sdk inbox and outbox. Generated once on 2026-09-28; never edited after it runs.

CREATE TABLE settings (
    id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY CHECK (id = 1),
    created_at  text COLLATE "C" NOT NULL
);

CREATE TABLE vip_creators (
    id            text COLLATE "C" PRIMARY KEY,
    kind          text COLLATE "C" NOT NULL CHECK (kind IN ('creator', 'network')),
    subject       text COLLATE "C" UNIQUE,
    username      text COLLATE "C",
    username_lc   text COLLATE "C" UNIQUE,
    display_name  text COLLATE "C",
    bio           text COLLATE "C",
    status        text COLLATE "C" NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'suspended')),
    origin        text COLLATE "C" NOT NULL DEFAULT 'self' CHECK (origin IN ('self', 'service', 'import', 'staff', 'system')),
    created_at    text COLLATE "C" NOT NULL,
    updated_at    text COLLATE "C" NOT NULL,
    CHECK ((kind = 'network' AND subject IS NULL) OR (kind = 'creator' AND subject IS NOT NULL))
);

CREATE TABLE vip_plans (
    id                  text COLLATE "C" PRIMARY KEY,
    creator_id          text COLLATE "C" NOT NULL REFERENCES vip_creators(id),
    slug                text COLLATE "C" NOT NULL,
    status              text COLLATE "C" NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published', 'archived')),
    billing_kind        text COLLATE "C" CHECK (billing_kind IS NULL OR billing_kind IN ('channel_subscription')),
    current_version_id  text COLLATE "C",
    latest_version      bigint NOT NULL DEFAULT 0,
    sort                bigint NOT NULL DEFAULT 0,
    created_by          text COLLATE "C",
    created_at          text COLLATE "C" NOT NULL,
    updated_at          text COLLATE "C" NOT NULL,
    archived_at         text COLLATE "C",
    UNIQUE (creator_id, slug)
);
-- Billing sells one channel subscription per (subscriber, creator) today, so a creator can have at
-- most one published plan bound to it.
CREATE UNIQUE INDEX idx_vip_plans_one_billing_product
    ON vip_plans (creator_id, billing_kind) WHERE status = 'published' AND billing_kind IS NOT NULL;

CREATE TABLE vip_plan_versions (
    id            text COLLATE "C" PRIMARY KEY,
    plan_id       text COLLATE "C" NOT NULL REFERENCES vip_plans(id),
    version       bigint NOT NULL,
    name          text COLLATE "C" NOT NULL,
    description   text COLLATE "C",
    benefits      text COLLATE "C" NOT NULL DEFAULT '[]',
    terms         text COLLATE "C" NOT NULL,
    change_note   text COLLATE "C",
    created_by    text COLLATE "C",
    created_at    text COLLATE "C" NOT NULL,
    published_at  text COLLATE "C",
    UNIQUE (plan_id, version)
);
CREATE FUNCTION vip_plan_versions_no_rewrite() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'vip_plan_versions are immutable: edit a plan by creating a new version'; END $$;
CREATE TRIGGER vip_plan_versions_no_rewrite BEFORE UPDATE ON vip_plan_versions FOR EACH ROW WHEN (NEW.id IS DISTINCT FROM OLD.id OR NEW.plan_id IS DISTINCT FROM OLD.plan_id OR NEW.version IS DISTINCT FROM OLD.version OR NEW.name IS DISTINCT FROM OLD.name OR NEW.description IS DISTINCT FROM OLD.description OR NEW.benefits IS DISTINCT FROM OLD.benefits OR NEW.terms IS DISTINCT FROM OLD.terms OR NEW.change_note IS DISTINCT FROM OLD.change_note OR NEW.created_by IS DISTINCT FROM OLD.created_by OR NEW.created_at IS DISTINCT FROM OLD.created_at OR (OLD.published_at IS NOT NULL AND NEW.published_at IS DISTINCT FROM OLD.published_at)) EXECUTE FUNCTION vip_plan_versions_no_rewrite();
CREATE FUNCTION vip_plan_versions_no_delete() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'vip_plan_versions are immutable: edit a plan by creating a new version'; END $$;
CREATE TRIGGER vip_plan_versions_no_delete BEFORE DELETE ON vip_plan_versions FOR EACH ROW EXECUTE FUNCTION vip_plan_versions_no_delete();

CREATE TABLE vip_perks (
    id           text COLLATE "C" PRIMARY KEY,
    creator_id   text COLLATE "C" NOT NULL REFERENCES vip_creators(id),
    key          text COLLATE "C" NOT NULL,
    name         text COLLATE "C" NOT NULL,
    description  text COLLATE "C",
    kind         text COLLATE "C" NOT NULL DEFAULT 'other' CHECK (kind IN ('badge', 'emote', 'gated_content', 'room', 'role', 'other')),
    status       text COLLATE "C" NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'retired')),
    created_by   text COLLATE "C",
    created_at   text COLLATE "C" NOT NULL,
    updated_at   text COLLATE "C" NOT NULL,
    UNIQUE (creator_id, key)
);

CREATE TABLE vip_plan_perks (
    plan_version_id  text COLLATE "C" NOT NULL REFERENCES vip_plan_versions(id),
    perk_id          text COLLATE "C" NOT NULL REFERENCES vip_perks(id),
    perk_key         text COLLATE "C" NOT NULL,
    perk_name        text COLLATE "C" NOT NULL,
    position         bigint NOT NULL DEFAULT 0,
    PRIMARY KEY (plan_version_id, perk_id)
);
CREATE INDEX idx_vip_plan_perks_key ON vip_plan_perks (plan_version_id, perk_key);
CREATE FUNCTION vip_plan_perks_no_update() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'vip_plan_perks belong to an immutable plan version'; END $$;
CREATE TRIGGER vip_plan_perks_no_update BEFORE UPDATE ON vip_plan_perks FOR EACH ROW EXECUTE FUNCTION vip_plan_perks_no_update();
CREATE FUNCTION vip_plan_perks_no_delete() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'vip_plan_perks belong to an immutable plan version'; END $$;
CREATE TRIGGER vip_plan_perks_no_delete BEFORE DELETE ON vip_plan_perks FOR EACH ROW EXECUTE FUNCTION vip_plan_perks_no_delete();

CREATE TABLE vip_product_bindings (
    id          text COLLATE "C" PRIMARY KEY,
    perk_id     text COLLATE "C" NOT NULL REFERENCES vip_perks(id),
    product     text COLLATE "C" NOT NULL,
    binding     text COLLATE "C" NOT NULL,
    config      text COLLATE "C" NOT NULL DEFAULT '{}',
    status      text COLLATE "C" NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'removed')),
    created_at  text COLLATE "C" NOT NULL,
    updated_at  text COLLATE "C" NOT NULL,
    UNIQUE (perk_id, product, binding)
);

CREATE TABLE vip_member_preferences (
    member_subject  text COLLATE "C" NOT NULL,
    creator_id      text COLLATE "C" NOT NULL REFERENCES vip_creators(id),
    show_badge      bigint NOT NULL DEFAULT 1,
    listed          bigint NOT NULL DEFAULT 0,
    updated_at      text COLLATE "C" NOT NULL,
    PRIMARY KEY (member_subject, creator_id)
);

CREATE TABLE vip_gated_resource_rules (
    id                text COLLATE "C" PRIMARY KEY,
    creator_id        text COLLATE "C" NOT NULL REFERENCES vip_creators(id),
    resource_service  text COLLATE "C" NOT NULL,
    resource_type     text COLLATE "C" NOT NULL,
    resource_id       text COLLATE "C" NOT NULL,
    requirement       text COLLATE "C" NOT NULL CHECK (requirement IN ('member', 'plan', 'perk')),
    plan_id           text COLLATE "C" REFERENCES vip_plans(id),
    perk_key          text COLLATE "C",
    sensitive         bigint NOT NULL DEFAULT 0,
    status            text COLLATE "C" NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
    created_by        text COLLATE "C",
    created_at        text COLLATE "C" NOT NULL,
    updated_at        text COLLATE "C" NOT NULL,
    CHECK (requirement <> 'plan' OR plan_id IS NOT NULL),
    CHECK (requirement <> 'perk' OR perk_key IS NOT NULL)
);
-- One active rule per (resource, creator): the product names the owner when it asks (policies.js).
DROP INDEX IF EXISTS idx_vip_rules_resource;
CREATE UNIQUE INDEX idx_vip_rules_resource_creator
    ON vip_gated_resource_rules (resource_service, resource_type, resource_id, creator_id) WHERE status = 'active';

CREATE TABLE vip_migration_maps (
    source        text COLLATE "C" NOT NULL,
    source_table  text COLLATE "C" NOT NULL,
    source_id     text COLLATE "C" NOT NULL,
    target_type   text COLLATE "C",
    target_id     text COLLATE "C",
    status        text COLLATE "C" NOT NULL CHECK (status IN ('imported', 'linked', 'held', 'excluded')),
    reason        text COLLATE "C",
    run_id        text COLLATE "C",
    created_at    text COLLATE "C" NOT NULL,
    updated_at    text COLLATE "C" NOT NULL,
    PRIMARY KEY (source, source_table, source_id)
);

CREATE TABLE vip_memberships (
    id                       text COLLATE "C" PRIMARY KEY,
    member_subject           text COLLATE "C" NOT NULL,
    creator_id               text COLLATE "C" NOT NULL REFERENCES vip_creators(id),
    plan_id                  text COLLATE "C" REFERENCES vip_plans(id),
    plan_version_id          text COLLATE "C" REFERENCES vip_plan_versions(id),
    billing_subscription_id  text COLLATE "C",
    origin                   text COLLATE "C" NOT NULL CHECK (origin IN ('checkout', 'billing', 'import')),
    joined_at                text COLLATE "C" NOT NULL,
    terms_since              text COLLATE "C" NOT NULL,
    updated_at               text COLLATE "C" NOT NULL,
    UNIQUE (member_subject, creator_id)
);
CREATE INDEX idx_vip_memberships_creator ON vip_memberships (creator_id);

CREATE TABLE vip_entitlement_projection (
    member_subject         text COLLATE "C" NOT NULL,
    creator_subject        text COLLATE "C" NOT NULL,
    kind                   text COLLATE "C" NOT NULL,
    active                 bigint NOT NULL,
    expires_at             text COLLATE "C",
    cancel_at_period_end   bigint NOT NULL DEFAULT 0,
    subscription_id        text COLLATE "C",
    subscription_status    text COLLATE "C",
    source                 text COLLATE "C" NOT NULL CHECK (source IN ('event', 'billing_check', 'import')),
    last_reason            text COLLATE "C",
    billing_event_id       text COLLATE "C",
    billing_as_of          bigint NOT NULL,
    synced_at              bigint NOT NULL,
    valid_until            bigint NOT NULL,
    last_used_at           bigint,
    PRIMARY KEY (member_subject, creator_subject, kind)
);
CREATE INDEX idx_vip_projection_creator ON vip_entitlement_projection (creator_subject, kind, active);

CREATE TABLE vip_checkouts (
    id                       text COLLATE "C" PRIMARY KEY,
    member_subject           text COLLATE "C" NOT NULL,
    creator_id               text COLLATE "C" NOT NULL REFERENCES vip_creators(id),
    plan_id                  text COLLATE "C" NOT NULL REFERENCES vip_plans(id),
    plan_version_id          text COLLATE "C" NOT NULL REFERENCES vip_plan_versions(id),
    provider                 text COLLATE "C" NOT NULL,
    status                   text COLLATE "C" NOT NULL CHECK (status IN ('created', 'handed_off', 'paid', 'failed', 'used')),
    billing_intent_id        text COLLATE "C",
    billing_subscription_id  text COLLATE "C",
    checkout_url             text COLLATE "C",
    checkout_ref             text COLLATE "C",
    error                    text COLLATE "C",
    created_at               text COLLATE "C" NOT NULL,
    updated_at               text COLLATE "C" NOT NULL
);
CREATE INDEX idx_vip_checkouts_member ON vip_checkouts (member_subject, creator_id, created_at);

-- openvibe-sdk/events inbox: one receipt per (consumer, event) handled
CREATE TABLE IF NOT EXISTS idempotency_receipts (
    consumer     text NOT NULL,
    event_id     text NOT NULL,
    processed_at bigint NOT NULL,
    PRIMARY KEY (consumer, event_id)
);

-- openvibe-sdk/events PostgreSQL outbox
CREATE TABLE IF NOT EXISTS event_outbox (
    id              bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    event_id        text NOT NULL UNIQUE,
    envelope        jsonb NOT NULL,
    traceparent     text,
    created_at      bigint NOT NULL,
    attempts        integer NOT NULL DEFAULT 0,
    next_attempt_at bigint NOT NULL DEFAULT 0,
    sent_at         bigint,
    seq             bigint,
    rejected_at     bigint,
    last_error      text
);
CREATE INDEX IF NOT EXISTS event_outbox_due ON event_outbox (next_attempt_at, id) WHERE sent_at IS NULL AND rejected_at IS NULL;
CREATE INDEX IF NOT EXISTS event_outbox_sent ON event_outbox (sent_at) WHERE sent_at IS NOT NULL;

-- Added after the first SQLite schema (server/db.js COLUMNS): the creator's choice to show their member count.
ALTER TABLE vip_creators ADD COLUMN show_member_count bigint NOT NULL DEFAULT 1;

-- The one settings row, and the network itself as the creator of network-wide plans and perks (an import replaces
-- both with the SQLite rows).
INSERT INTO settings (id, created_at) VALUES (1, to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')) ON CONFLICT DO NOTHING;
INSERT INTO vip_creators (id, kind, subject, username, username_lc, display_name, origin, created_at, updated_at)
    VALUES ('network', 'network', NULL, NULL, NULL, 'OpenVibe', 'system',
            to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'), to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"'))
    ON CONFLICT DO NOTHING;
